### ISSUE TITLE
I can not get anydata, i think value is wrong

### ISSUE THREAD

**Issue by BananaRR** [cskollar/zabbix-oneview#2]
var result = [],
    req = new HttpRequest(),resp;
    req.AddHeader('content-type: application/json');
    req.AddHeader('x-api-version: 1000');

    //GET Token
    resp = req.post('https://{$ONEVIEW_HOST}/rest/login-sessions',**value**);
    if (req.getStatus() != 200) {
        throw 'Response code: '+req.getStatus();
    }
    resp = JSON.parse(resp);
    token = resp.sessionID;

please tell me value mean?

value  指定了那些值？从哪里可以看
What values are specified for value? Where can I see it
<img width="454" alt="企业微信截图_16932152952532" src="https://github.com/cskollar/zabbix-oneview/assets/33884722/5ebbeb43-571b-4882-8e69-abe92699cea6">

**Comment by cskollar** [comment]
In Zabbix script type items, the 'value' variable contains a JSON string that includes the parameters set for the item (parameters seciton at the item's settings):
https://www.zabbix.com/documentation/6.0/en/manual/config/items/itemtypes/script

In the case of a OneView template, the 'value' contains the values of {$ONEVIEW_PASS} and {$ONEVIEW_USER} macros:

![Screenshot 2023-08-28 at 13 29 29](https://github.com/cskollar/zabbix-oneview/assets/46558488/088c7cfd-0db1-4c59-a771-d8cfc7608a5b)
